spring:
  application:
    name:blogPlatform
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db
    username: luready
    password: dldbwns6420
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO
    org.example.blogPlatform: DEBUG